# GitHub Actions workflow for BIDS Apps Brainstorm
# Phase 4 - To be implemented

name: CI/CD Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Build MCR image
      run: |
        docker build -f Dockerfile.mcr -t bids-apps-brainstorm:mcr .
    
    - name: Run smoke tests
      run: |
        chmod +x tests/smoke.sh
        ./tests/smoke.sh
    
    - name: Run BIDS validation
      run: |
        chmod +x tools/bids_validate.sh
        ./tools/bids_validate.sh tests/tiny_bids_meg

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2
    
    - name: Login to registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      run: |
        docker build -f Dockerfile.mcr -t bids-apps-brainstorm:latest .
        docker push bids-apps-brainstorm:latest